<?
$page_id = 'terms-and-conditions';
$title = "Terms & Conditions";
template::inc('website', 'top');
?>

<h1 class="module-bar">Terms &amp; Conditions</h1>

<p><strong>1. Your Acceptance </strong></p>
<p>BY USING OR VISITING THIS WEBSITE (together with all Content available through  the <?=$domain?> domain name and other sites owned, operated or controlled by <?=$company_legal_name?>, the "Website"), OR SUBMITTING CONTENT TO THIS WEBSITE, YOU SIGNIFY YOUR ASSENT  TO (1) THESE TERMS AND CONDITIONS (the "Terms &amp; Conditions"), AND (2) <?=strtoupper($company_name)?>'S PRIVACY  POLICY at <a href="/privacy-policy">www.<?=$domain?>/privacy-policy</a>.  These Terms &amp; Conditions apply to all users of the Website.  If you do not agree to these Terms &amp; Conditions or the Privacy Policy, then please do not use  the Website. </p>
<p><strong>2. Links </strong></p>
<p>The Website may contain links to third party websites that are not owned or controlled  by <?=$company_name?>. <?=$company_name?> is not affiliated with those websites, has no control over,  and assumes no responsibility for, the content, privacy policies, or practices of  any third party websites. In addition, <?=$company_name?> will not and cannot censor or edit  the content of any third-party site. By using the Website, you expressly release  <?=$company_name?> from any and all liability arising from your use of any third-party website.  Accordingly, we encourage you to be aware when you have left the Website and to  read the terms and conditions and privacy policy of each other website that you  visit. </p>
<p><strong>3. Website Access </strong></p>
<ol>
<li><?=$company_name?> hereby grants you permission to use the Website, provided that:  	(i) your use of the Website is solely for your personal, noncommercial use;  	(ii) you will not copy, distribute or modify any part of the Website without  	<?=$company_name?>'s prior written authorization; (iii) you will not send unsolicited  	or unauthorized advertisements, spam, chain letters, etc., (iv) you will not  	transmit any Content which contains software viruses, or other harmful computer  	code, files or programs; (v) you will not disrupt servers or networks connected  	to the Website; and (vi) you comply with these Terms &amp; Conditions. </li>
<li>In order to access some features of the Website, you will have to create  	an account. You may never use another's account without permission. When creating  	your account, you must provide accurate and complete information. You are solely  	responsible for the activity that occurs on your account, and you must keep  	your account password secure. You must notify <?=$company_name?> immediately of any breach  	of security or unauthorized use of your account. You will be liable for any  	use made of your account or password and the losses of <?=$company_name?> or others due  	to such unauthorized use. <?=$company_name?> will not be liable for your losses caused  	by any unauthorized use of your account. </li>
<li>You agree not to use or launch any automated system, including without limitation,  	"robots," "spiders," and "offline readers," that accesses the Website in a manner  	that sends more request messages to the <?=$company_name?> servers in a given period of  	time than a human can reasonably produce in the same period by using a conventional  	on-line web browser. <?=$company_name?> grants the operators of public search engines  	permission to use spiders to copy materials from the Website for the sole purpose  	of creating publicly available searchable indices of the materials, but not  	caches or archives of such materials. <?=$company_name?> reserves the right to revoke  	these exceptions either generally or in specific cases. You agree not to collect  	or harvest any personally identifiable information, including account names  	or e-mail addresses, from the Website, nor to use the communication systems  	provided by the Website for any commercial solicitation purposes. You agree  	not to solicit, for commercial purposes, any users of the Website with respect  	to their User Submissions (as defined below). </li>
<li><?=$company_name?> has the right to terminate your access to the Website, in its sole  	discretion, immediately and with or without cause. </li>
</ol>
<p><strong>4. Intellectual Property Rights </strong></p>
<p>The content on the Website, including all User Submissions, including without  limitation, the text, software, scripts, graphics, photos, sounds, music, videos  and interactive features ("Content") and the trademarks, service marks and logos  contained therein ("Marks"), are owned by or licensed to <?=$company_name?>. Content on the  Website is provided to you "AS IS" for your information and personal use only and  may not be used, copied, distributed, transmitted, broadcast, displayed, sold, licensed,  reverse engineered, de-compiled, or otherwise exploited for any other purposes whatsoever  without <?=$company_name?>'s prior written consent. <?=$company_name?> reserves all rights not expressly  granted in and to the Website. If you download or print a copy of the Content for  personal use, you must retain all copyright and other proprietary notices contained  therein. You agree not to circumvent, disable or otherwise interfere with security-related  features of the Website or features that prevent or restrict use or copying of any  Content or enforce limitations on use of the Website. </p>
<p><strong>5. User Submissions </strong></p>
<ol>
<li>The Website facilitates the submission of videos or other Content by you  	and other users ("User Submissions") and the hosting and publishing of such  	User Submissions. You understand that whether or not such User Submissions are  	published, <?=$company_name?> does not guarantee any confidentiality with respect to any  	User Submissions. <?=$company_name?> has complete discretion whether to accept or reject  	your User Submission, or to transfer your User Submission from one <?=$company_name?>  	program to another program or portion of the Website. </li>
<li>You shall be solely responsible for your own User Submissions and the consequences  	of posting or publishing them. You represent and warrant that: (i) you own or  	have the necessary rights and permissions to use and authorize <?=$company_name?> to use  	all copyright, trademark or other proprietary rights in and to any User Submissions  	to enable inclusion and use thereof as contemplated by the Website and these  	Terms &amp; Conditions; and (ii) you have the written consent and/or permission of each  	and every identifiable individual person in the User Submission to use their  	name or likeness as contemplated by the Website and these Terms &amp; Conditions. </li>
<li>You retain all of your ownership rights in your User Submissions. However,  	by submitting the User Submissions to <?=$company_name?>, you hereby grant <?=$company_name?>, in  	addition to any other rights which it has pursuant to any other program established  	by <?=$company_name?>, a worldwide, non-exclusive and transferable license to use, copy,  	prepare derivative works of (including without limitation, to rename, edit,  	shorten, split the videos into different segments, and use the entire video  	or segments as part of compilations), display, and perform the User Submissions  	in connection with the Website and <?=$company_name?>'s (and its successor's) business,  	including without limitation to grant access to the Website to third parties  	to view the User Submission (and derivative works thereof). With regard to User  	Submissions submitted under any Program or not submitted under any  	other special program, you may notify <?=$company_name?> to remove the User Submission  	from the Website, and <?=$company_name?> will do so within a reasonable time period, at  	which point the foregoing license to <?=$company_name?> will terminate. </li>
<li>You also hereby grant each user of the Website or other viewer of the User  	Submission a non-exclusive right to use, reproduce, distribute, prepare derivative  	works of, display and perform such User Submissions, all for non-commercial  	and personal use. </li>
<li>You agree that you will not: (i) submit material that is copyrighted, protected  	by trade secret or otherwise subject to third party proprietary rights, including  	privacy and publicity rights, unless you are the owner of such rights or have  	permission from their rightful owner to post the User Submission and to grant  	<?=$company_name?> all of the license rights granted herein; (ii) publish falsehoods or  	misrepresentations that could damage <?=$company_name?> or any third party; (iii) submit  	material that is unlawful, obscene, defamatory, libelous, threatening, pornographic,  	harassing, hateful, racially or ethnically offensive, or encourages conduct  	that would be considered a criminal offense, give rise to civil liability, violate  	any law, or is otherwise inappropriate; or (iv) misidentify yourself in submitting  	the User Submission or misstate your true identity. <?=$company_name?> does not endorse  	any User Submission or any opinion, recommendation, or advice expressed therein,  	and <?=$company_name?> expressly disclaims any and all liability in connection with User  	Submissions. </li>
<li>You understand that when using the Website, you will be exposed to User  	Submissions from a variety of sources, and that <?=$company_name?> is not responsible  	for the accuracy, usefulness, safety, or intellectual property rights of or  	relating to such User Submissions. You may be exposed to User Submissions that  	are inaccurate, offensive, indecent, or objectionable, and you agree to waive,  	and hereby do waive, any legal or equitable rights or remedies you may have  	against <?=$company_name?> with respect thereto, and agree to indemnify and hold <?=$company_name?>,  	its owners, affiliates, employees, agents and/or licensors, harmless to the  	fullest extent allowed by law regarding all matters related to your use of the  	Website. You acknowledge that access to certain Content which may be available  	through the Website and which depict violence, or contain images of nudity,  	sexual acts, or other sexual material ("Mature Content") is permitted only if  	you are over the minimum age applicable in your jurisdiction (often but not  	necessarily 18 or 21). </li>
</ol>
<p><strong>6. Copyright and Content Policy </strong></p>
<p><?=$company_name?> respects the intellectual property rights of others, and requests you  to do the same. <?=$company_name?> does not permit copyright infringing activities and infringement  of intellectual property rights on its Website, and <?=$company_name?> will remove all Content  if properly notified that such Content infringes on another's intellectual property  rights. <?=$company_name?> reserves the right to remove Content without prior notice. <?=$company_name?>  will also terminate a User's access to the Website, if they are determined to be  a repeat infringer. <?=$company_name?> may remove such Content and/or terminate a User's access  for uploading such Content in violation of these Terms &amp; Conditions at any time, without  prior notice and at its sole discretion. </p>
<p>If you believe that your Content has been copied in a way that constitutes copyright  infringement, please provide <?=$company_name?>'s Copyright Agent the following information: </p>
<ol>
<li>an electronic or physical signature of the person authorized to act on behalf  	of the owner of the copyright;</li>
<li>a description of the copyrighted work that you claim has been infringed,  	including the URL (web page address) of the location where the copyrighted work  	exists or a copy of the copyrighted work; </li>
<li>a description of where the material that you claim is infringing is located  	on the Website, including the URL; </li>
<li>your address, telephone number, and email address; </li>
<li>a statement by you that you have a good faith belief that the disputed use  	is not authorized by the copyright owner, its agent, or the law; and </li>
<li>a statement by you, made under penalty of perjury, that the above information  	in your Notice is accurate and that you are the copyright owner or authorized  	to act on the copyright owner's behalf. </li>
</ol>
<p><?=$company_name?>'s Copyright Agent for Notice of claims of copyright infringement can  be reached as follows: </p>
<p><?=$company_legal_name?> <br>
<?=$address?><br /><br>
By email: <a href="mailto:<?=$support_email?>"><?=$support_email?></a>&nbsp; </p>
<p>Please also note that under Section 512(f) of the US Copyright Act any person  who knowingly materially misrepresents that material or activity is infringing may  be subject to liability. </p>
<p><strong>7. Warranty Disclaimer </strong></p>
<p>YOU AGREE THAT YOUR USE OF THE WEBSITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST  EXTENT PERMITTED BY LAW, <?=strtoupper($company_name)?>, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS  DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND  YOUR USE THEREOF. <?=strtoupper($company_name)?> MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY  OR COMPLETENESS OF THE WEBSITE'S CONTENT AND ASSUMES NO LIABILITY FOR ANY (I) MISTAKES  OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE RESULTING FROM  YOUR USE OF THE WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS  AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN,  (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITE, (IV)  ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH  OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT  OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT  ON OR VIA THE WEBSITE. <?=strtoupper($company_name)?> DOES NOT WARRANT, ENDORSE OR ASSUME RESPONSIBILITY  FOR ANY CONTENT, OR PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH  THE WEBSITE OR FEATURED IN ANY ADVERTISING, AND <?=strtoupper($company_name)?> WILL NOT BE A PARTY TO  OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY  PROVIDERS OF PRODUCTS OR SERVICES. </p>
<p><strong>8. Limitation of Liability </strong></p>
<p>IN NO EVENT SHALL <?=strtoupper($company_name)?>, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE  LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL  DAMAGES WHATSOEVER RESULTING FROM ANY (I) CONTENT, INCLUDING ANY MISTAKES OR INACCURACIES  THEREIN, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING  FROM YOUR USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED USE OF OUR SERVERS AND/OR ANY  AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY  INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS,  VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR  WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR  FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT  ON OR VIA THE WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL  THEORY, AND WHETHER OR NOT <?=strtoupper($company_name)?> IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED  BY LAW IN THE APPLICABLE JURISDICTION. </P>
<P>YOU SPECIFICALLY ACKNOWLEDGE THAT <?=strtoupper($company_name)?> SHALL NOT BE LIABLE FOR USER SUBMISSIONS  OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE  RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. </p>
<p><strong>9. Indemnity </strong></p>
<p>You agree to defend, indemnify and hold harmless <?=$company_name?>, its affiliates, and  their respective officers, directors, employees and agents, from and against any  and all claims, damages, obligations, losses, liabilities, costs and expenses (including  but not limited to attorney's fees) arising from: (i) your use of the Website; (ii)  your violation of these Terms &amp; Conditions; (iii) your violation of the terms which apply  to your User Submission; (iv) your violation of any third party right, including  without limitation any copyright, property, publicity or privacy right; or (v) any  claim that one of your User Submissions caused damage to a third party. This defense  and indemnification obligation will survive these Terms &amp; Conditions and your use of the  Website. </p>
<p><strong>10. Ability to Accept Terms &amp; Conditions </strong></p>
<p>You affirm that you are either more than 18 years of age or possess legal parental  or guardian consent to enter into these Terms &amp; Conditions, and to comply with these Terms  of Use. In any case, you affirm that you are over the age of 13, as the Website  is not intended for children under 13. If you are under 13 years of age, then please  do not use the Website-there are lots of other great web sites for you. Talk to  your parents about what sites are appropriate for you. </p>
<p><strong>11. Assignment </strong></p>
<p>These Terms &amp; Conditions, and any rights and licenses granted hereunder, may not be  transferred or assigned by you, but may be assigned by <?=$company_name?> without restriction. </p>
<p><strong>12. General </strong></p>
<p>You agree that: (i) the Website shall be deemed solely based in <?=$legal_state?>; and  (ii) the Website shall be deemed a passive website that does not give rise to personal  jurisdiction over <?=$company_name?>, either specific or general, in jurisdictions other than  the State of <?=$legal_state?>. These Terms &amp; Conditions shall be governed by the internal substantive  laws of the State of <?=$legal_state?>, without respect to its conflict of laws principles.  Any claim or dispute between you and <?=$company_name?> that arises in whole or in part from  the Website or these Terms &amp; Conditions shall be decided exclusively by a federal or state  court of competent jurisdiction located in <?=$legal_city?>, <?=$legal_state?>. These Terms &amp; Conditions,  together with the Privacy Policy at <a href="/privacy-policy">www.<?=$domain?>/privacy-policy</a> and one of the following two terms and conditions: Terms for any Program, and any other legal notices  published by <?=$company_name?> on the Website, shall constitute the entire agreement between  you and <?=$company_name?> concerning the Website. If any provision of these Terms &amp; Conditions  is deemed invalid by a court of competent jurisdiction, the invalidity of such provision  shall not affect the validity of the remaining provisions of these Terms &amp; Conditions,  which shall remain in full force and effect. No waiver of any term of this these  Terms &amp; Conditions shall be deemed a further or continuing waiver of such term or any  other term, and a party's failure to assert any right or provision under these Terms  of Use shall not constitute a waiver of such right or provision. <?=$company_name?> reserves  the right to amend these Terms &amp; Conditions at any time and without notice, and it is  your responsibility to review these Terms &amp; Conditions for any changes. Your use of the  Website following any amendment of these Terms &amp; Conditions will signify your assent to  and acceptance of its revised terms. YOU AND <?=strtoupper($company_name)?> AGREE THAT ANY CAUSE OF ACTION  ARISING OUT OF OR RELATED TO THE <?=strtoupper($company_name)?> WEBSITE MUST COMMENCE WITHIN ONE (1) YEAR  AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY  BARRED. </p>
<p>Last updated: <?=$last_updated_terms?>.</p>

<?
template::inc('website', 'bottom');
?>